Upgrade Zookeeper dependency to 3.5.7 and Curator to 4.3.0
apache/phoenix pull request #1434
Opened 2022-05-06 09:48 UTC by wendigo

Previous Zookeeper version was broken on JDK 14+ due to the incorrect usage of
InetSocketAddress.toString. For reference see: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8232369

2022-05-06 09:49 UTC, wendigo commented
cc @stoty 

This is relevant for the https://github.com/trinodb/trino project as we want to move to JDK17 (which is the LTS)

2022-05-06 16:25 UTC, vincentpoon approved these changes
+1 assuming tests pass

2022-05-09 06:21 UTC, stoty commented
Please open a JIRA, and add JIRA-XXXXX to the commit description, @wendigo.

2022-05-09 06:35 UTC, stoty commented
The ZK version doesn't do anything for ZK on master, we're already using 3.5.7 for both 2.3 and 2.4. (set in the hbase profiles)

Please remove the ZK version overrides from the hbase profiles in the pom, as they are not needed with this change.

As for Curator, HBase uses 4.2, not 4.3 on branch 2.3, 2.4, and 2.5. Is there a particular reason for using 4.3, or did you just pick the latest 4.3 release ?

In case you also want this merged into 5.1, we'd also have to check if HBase 2.1 and 2.2 works with ZK 3.5.7 (IIRC it does)

2022-05-09 06:39 UTC, stoty requested changes

2022-05-09 06:39 UTC, stoty commented on pom.xml
> +    <zookeeper.version>3.5.7</zookeeper.version>
Please remove the corresponding overrides from the profiles.

2022-05-09 06:39 UTC, stoty commented on pom.xml
> +    <curator.version>4.3.0</curator.version>
HBase uses 4.2.
While it's probably OK to use a newer version, if there is no particular reason to use 4.3, it's better to stick with the version HBase uses.

2022-06-02 15:15 UTC, gjacoby126 commented
@vincentpoon @wendigo - I think this PR is currently waiting for changes that have been requested by @stoty and then I think would be ready for commit. Do you have bandwidth to get back to this in time for the Phoenix 5.2 release (probably in the next month or so?)

2022-06-02 17:16 UTC, wendigo commented
@gjacoby126 I will update this PR soon

2022-06-02 20:45 UTC, wendigo commented
@stoty @gjacoby126 PR updated. I tested it with patched Trino version, and now it works correctly on JDK 17 with HBase 2.3.0

2022-06-03 12:29 UTC, gjacoby126 commented
@wendigo - the changes to the pom look good, but could you please change the commit message to refer to a JIRA number. (And if there isn't a JIRA for this yet, could you please create on on issues.apache.org.) Thanks!

2022-06-03 12:40 UTC, wendigo commented
@gjacoby126 yes, will do, I need to create jira account first.

2022-06-03 17:49 UTC, wendigo commented
@gjacoby126 done, JIRA handle is the same as in GitHub (@wendigo). I've updated the commit message too.

2022-06-03 17:49 UTC, wendigo commented
https://issues.apache.org/jira/browse/PHOENIX-6723

2022-06-03 21:48 UTC, gjacoby126 approved these changes
+1, thanks @wendigo . @stoty , did you want any other changes to this patch before we commit it?

2022-06-07 12:15 UTC, stoty approved these changes
+1 LGTM.
Thank you.

2022-06-07 15:21 UTC, merged