PHOENIX-6627 remove tephra references - WIP
apache/phoenix pull request #1455
Opened 2022-06-20 09:21 UTC by zsgyulavari

2022-06-20 18:10 UTC, gjacoby126 commented
Thanks for taking this up, @zsgyulavari ! Please let me know if there's anything I can do to help -- it would be great if we could get this into 5.2 which is coming soon. 

On the first pass it looks like there are 151 test failures, but most of them seem to be from the same problem in TransactionFactory$Provider's fromCode method. On line 69 it's making an assumption that the length of the Provider enum is equal to the largest Provider enum value (that is, there are 2 providers, and the highest provider is enum value 2.) That's not true anymore now that the Tephra provider is gone, so the logic has to change.

2022-06-20 18:11 UTC, gjacoby126 commented
Also, what will happen to user tables who upgrade from Phoenix 5.1 -> 5.2 and have the Provider set to Tephra? Would that cause the region to crash from trying to load an enum value that doesn't exist? If so, what sort of upgrade logic should we include? I can think of three options:
 1. Switch tables to non-transactional 
 2. Switch tables to Omid 
 3. Keep the Tephra enum and just WARN or ERROR on region load that it doesn't do anything 

1 and 2 are both tricky to coordinate on a rolling restart, because the normal upgrade logic runs when SYSTEM.CATALOG is upgraded, but the crashing would probably come before that, when a region hosting a TEPHRA-enabled table has its region server upgraded. But I worry that some operators would miss the warning in their logs. 
 
@stoty @jpisaac @kadirozde @virajjasani , curious on your opinions.

2022-08-09 05:08 UTC, stoty requested changes

2022-08-09 05:08 UTC, stoty commented on phoenix-core/src/main/java/org/apache/phoenix/transaction/TransactionFactory.java
> +        OMID((byte)2, OmidTransactionProvider.getInstance());
This changes the ordinal, which SHOULD not be a real problem as we don't use that for serialization, but keeping TEPHRA, and just renaming it to something like TEPHRA_REMOVED would possibly also make it easier to handle the hairy cases where tephra defined for old tables.

2022-08-09 05:08 UTC, stoty commented on phoenix-core/src/main/java/org/apache/phoenix/transaction/TransactionFactory.java
> +                ? Provider.OMID
Again, should we just error out ?

2022-08-09 05:08 UTC, stoty commented on phoenix-core/src/test/java/org/apache/phoenix/util/TestUtil.java
> +    	//TODO: remove this method altogether
Yes, it shouldn't be too difficult.

2022-08-09 05:08 UTC, stoty commented on phoenix-core/src/main/java/org/apache/phoenix/transaction/NotAvailableTransactionProvider.java
> +        return TransactionFactory.Provider.OMID;
This is not right.
We should either return null, or the UnavailableProvider's type, if we keep that,

2022-08-09 05:35 UTC, stoty commented on phoenix-core/src/it/java/org/apache/phoenix/end2end/index/ImmutableIndexIT.java
>      				{ true, false, null, false }, { true, false, null, true },
Correction:
Those seem to be unsupported operations for Omid, so this is fine.

2022-08-10 21:39 UTC, apurtell commented
I'm going to close this PR but we can reopen it if the alternative PR I am about to open is not acceptable for some reason.

2022-08-10 21:39 UTC, closed without merging