PHOENIX-6918 :- ScanningResultIterator should not retry when the query times out
apache/phoenix pull request #1589
Opened 2023-04-07 00:58 UTC by lokiore

2023-04-14 17:14 UTC, gjacoby126 requested changes
Looks good, just a couple of nits

2023-04-14 17:14 UTC, gjacoby126 commented on phoenix-core/src/main/java/org/apache/phoenix/iterate/ScanningResultIterator.java
> +                            ". Query couldn't be completed in the allotted time at ScanningResultIterator: "
nit: We probably shouldn't be mentioning Phoenix internals like ScanningResultIterator in an error message that goes back to end-users.

2023-04-14 17:14 UTC, gjacoby126 commented on phoenix-core/src/it/java/org/apache/phoenix/end2end/MapReduceIT.java
> +    private void createPagedJobAndTestFailedJobDueToTimeOut(Connection conn, String s, double v, String tenantId,
nit: function-level variables should have meaningful names more than 1 character (not "s" or "v"). (For temp variables in a loop this would be fine)

2023-04-14 23:56 UTC, lokiore commented
@gjacoby126, addressed the nits. 
Thanks for reviewing !

2023-04-17 17:06 UTC, merged

2023-04-17 18:04 UTC, lokiore commented
@gjacoby126  Thanks for merging, do I need to create a separate PR for 5.1 or this can be directly committed !?