PHOENIX-7172: Support HBase 2.6
apache/phoenix pull request #1793
Opened 2024-01-11 14:36 UTC by richardantal

Remove files left from Hbase 2.3 compat module

2024-01-11 14:39 UTC, richardantal commented
I removed the HBase 2.3 compat module as it should have been removed in [PHOENIX-6877](https://issues.apache.org/jira/browse/PHOENIX-6877)
And added the new 2.6 modules, git recognises these as renamed some files which is not ideal, maybe it should be done separately.
Also this change can only be merged after the 2.6 release

2024-01-11 15:34 UTC, stoty commented
We still have time, I agree that it'd be cleaner if we removed any 2.3 leftovers in a separate ticket.

2024-01-15 12:59 UTC, stoty commented
Please update the commit message, @richardantal

2024-01-15 13:14 UTC, stoty requested changes

2024-01-15 13:14 UTC, stoty commented on pom.xml
> +    <profile>
nit:
Please keep the ascending order, and move this under the 2.5 profiles.

2024-01-16 06:06 UTC, stoty commented
Thank you.
Let's get get back to this once 2.6.0 is out.

2024-01-16 06:07 UTC, stoty reviewed
removing "request changes" state

2024-02-28 15:27 UTC, stoty commented on phoenix-hbase-compat-2.6.0/src/main/java/org/apache/phoenix/compat/hbase/CompatIndexHalfStoreFileReader.java
> +        super(readerContext, hFileInfo, cacheConf, new StoreFileInfo(conf, fs, new Path(fs.getHomeDirectory().toUri()),
This is broken.

You need to pass the Path here, and use it directly.

2024-02-28 15:29 UTC, stoty commented on phoenix-hbase-compat-2.6.0/src/main/java/org/apache/phoenix/compat/hbase/CompatIndexHalfStoreFileReader.java
> +        super(readerContext, hFileInfo, cacheConf, new StoreFileInfo(conf, fs, new Path(fs.getHomeDirectory().toUri()),
This will point to the FS root, and fail.
At least fails on 3.0, and it doesn't ,make sense either.

2024-03-21 11:55 UTC, stoty commented on phoenix-hbase-compat-2.6.0/src/main/java/org/apache/phoenix/compat/hbase/CompatIndexHalfStoreFileReader.java
> +        super(readerContext, hFileInfo, cacheConf, new StoreFileInfo(conf, fs, new Path(fs.getHomeDirectory().toUri()),
You can see how I fixed this in #1815

2024-06-06 05:42 UTC, virajjasani commented
Now that HBase 2.6.0 is released, we can resume here?

2024-06-17 03:57 UTC, stoty commented
Kicked off a new CI build

2024-06-17 04:01 UTC, stoty commented
Can you rebase @richardantal ? The patch doesn't apply cleanly anymore.

2024-06-17 04:02 UTC, stoty commented
It is based on an old version, from before we removed 2.4.0. support from HEAD.

2024-06-17 04:11 UTC, stoty commented
Also this still uses 2.6.0-SNAPSHOT.
Updating to 2.6.0-hadoop3 should let the CI run fully.

2024-06-17 04:51 UTC, stoty commented
Also update the Phoenix version to 5.3.0-SNAPSHOT in the new compatibility module, I've spent an hour trying to compile it.

2024-06-17 05:01 UTC, stoty commented
CompatOmidTransactionTable also needs to be updated.

2024-06-17 08:45 UTC, stoty commented
I see that hose issues are fixed.

Sorry, I must have used an older patch.

2024-06-17 08:47 UTC, stoty commented
However, most of the checkstyle warnings are relevant.

I'm not sure why the javadoc check failed.

2024-06-18 04:07 UTC, stoty approved these changes
+1 LGTM.

I have no idea why the javadoc check has failed, but I can't see anything wrong in the patch that could have caused that.

2024-06-18 04:27 UTC, virajjasani commented
Does this work fine locally?
`mvn clean javadoc:javadoc -Dskip.code-coverage  -DskipTests=true`

2024-06-18 05:47 UTC, stoty commented
Yes, it works after mvn install.
Yetus should have taken care of that.

2024-06-18 10:32 UTC, merged

2024-06-18 21:03 UTC, virajjasani commented
Looks like we need to add support to run tests against 2.6 profile https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-mulitbranch/job/master/688/ ?

2024-06-19 07:12 UTC, stoty commented
Yes, opened https://issues.apache.org/jira/browse/PHOENIX-7333 for that.

2024-06-20 07:11 UTC, virajjasani commented
Thanks @stoty @richardantal for this great work!

Reg the precommit jenkins builds, i just noticed that 2.6 builds are getting aborted (whereas 2.4 and 2.5 builds get failed with few test failures but at least the builds are not aborted).

2024-06-20 07:18 UTC, stoty commented
You mean the multibranch jenkis job, @virajjasani  ?
We all precommit builds are running with 2.5 only at the moment.

2024-06-20 07:20 UTC, virajjasani commented
My bad, yes multibranch builds of master and 5.2

2024-06-20 08:50 UTC, stoty commented
Opened https://issues.apache.org/jira/browse/PHOENIX-7339

2024-07-12 18:56 UTC, virajjasani commented
Thanks a lot @stoty @richardantal for getting HBase 2.6 support in and stabilizing tests.
It seems like one last thing we might have to do is adjust client version for 2.6 profile? https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-mulitbranch/job/master/703/testReport/junit/org.apache.phoenix.end2end/BackwardCompatibilityIT/MatrixBuild___Matrix___HBASE_PROFILE____2_6____BuildAndTest___initializationError/